version: '3'
services:
  app:
    build: app
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - PORT=8000
  web:
    build: web
    volumes:
      - ./web:/web
    ports:
      - 4200:4200
